version: '3.8'
services:
  app:
    container_name: nedtraks-api
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - postgresql
  
  postgresql:
    container_name: nedtraks-postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - nedtraks-postgres:/var/lib/postgresql/data

  pg-admin4:
    container_name: nedtraks-pg-admin
    image: dpage/pgadmin4
    env_file:
     - ./.env
    ports:
     - "5050:80"

volumes:
 nedtraks-postgres: {}